### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by MakironiMan** [Pewaukee-Watershed/pewaukee-watershed.github.io#8]
I like this palette. What do you think @secnyt https://coolors.co/f5f5f5-c2c2c2-858585-121619.

**Comment by KhajasJS** [comment]
@MakironiMan How would this color pallete change the main page? Right now there are four colorful colors, so there seems to be an already established color pallete. 
![Screenshot 2020-11-03 at 11 03 32 AM](https://user-images.githubusercontent.com/57632215/98017055-57df9c80-1dc4-11eb-841b-2bfde2dd9819.png).

Would you keep the existing colors, or switch to the new color pallete?

**Comment by secnyt** [comment]
The color palette from Tejas is fine, although it does not have color. Those colors (and maybe a few inbetween) can be just the grayscale palette, maybe?
